In [11]:
import pandas as pd


def loadData():
    df = pd.read_csv('./data/car_eval.csv')
    df.columns = ['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'class']
    return df

df = loadData()
df.head(100)

   buying  maint  doors persons lug_boot safety  class
0   vhigh  vhigh      2       2    small    med  unacc
1   vhigh  vhigh      2       2    small   high  unacc
2   vhigh  vhigh      2       2      med    low  unacc
3   vhigh  vhigh      2       2      med    med  unacc
4   vhigh  vhigh      2       2      med   high  unacc
..    ...    ...    ...     ...      ...    ...    ...
95  vhigh  vhigh  5more       4      big    low  unacc
96  vhigh  vhigh  5more       4      big    med  unacc
97  vhigh  vhigh  5more       4      big   high  unacc
98  vhigh  vhigh  5more    more    small    low  unacc
99  vhigh  vhigh  5more    more    small    med  unacc

[100 rows x 7 columns]

In [26]:
def findS(data, target='unacc'):
    # Transform 'class' column to boolean indicating whether it matches the target value
    data['class'] = data['class'] == target
    
    # Initialize hypothesis
    hypothesis = ['?'] * (len(data.columns) - 1)
    
    # Iterate over rows in the DataFrame
    for index, instance in data.iterrows():
        if instance['class']:  # Positive example
            for i, attribute in enumerate(instance[:-1]):  # Exclude the 'class' column
                if hypothesis[i] == '?':
                    hypothesis[i] = attribute
                elif hypothesis[i] != attribute:
                    hypothesis[i] = '*'
    
    return hypothesis

data = findS(loadData())
print(data)

['*', '*', '*', '*', '*', '*']

In [ ]:
# Define the training data
training_data = [
    ('Sunny', 'Warm', 'Normal', 'Strong', 'Warm', 'Same', True),
    ('Sunny', 'Warm', 'High', 'Strong', 'Warm', 'Same', True),
    ('Rainy', 'Cold', 'High', 'Strong', 'Warm', 'Change', False),
    ('Sunny', 'Warm', 'High', 'Strong', 'Cool', 'Change', True)
]

# Initialize the hypothesis
hypothesis = ['?', '?', '?', '?', '?', '?']

# Perform Find-S algorithm
for instance in training_data:
    if instance[-1]:  # Positive example
        for i in range(len(instance) - 1):
            if hypothesis[i] == '?':
                hypothesis[i] = instance[i]
            elif hypothesis[i] != instance[i]:
                hypothesis[i] = '*'

# Print the final hypothesis
print("Final hypothesis:", hypothesis)

Final hypothesis: ['Sunny', 'Warm', '*', 'Strong', '*', '*']